---
strict: true
site_name: wiktionary
site_description: Wiktionary on-demand scrapper.
site_url: https://proofit404.github.io/wiktionary
theme:
  name: material
  palette:
    scheme: default
    primary: deep-purple
    accent: deep-purple
  icon:
    logo: material/language-python
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
repo_name: proofit404/wiktionary
repo_url: https://github.com/proofit404/wiktionary
edit_uri: ""
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - javascripts/extra.js
nav:
  - Home:
      - Home: index.md
      - Installation: installation.md
      - Changelog: changelog.md
