#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

docker build --tag devweapon .

docker run --rm --volume=.:/src --interactive --tty devweapon:latest bash -c '
  . $HOME/.nvm/nvm.sh
  ./scripts/install
'
