---
name: pipeline
"on":
  push:
    branches:
      - release
  pull_request:
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0
      - run: |
          git checkout $GITHUB_HEAD_REF
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.3
      - uses: actions/setup-node@v4
        with:
          node-version: 22.6.0
      - run: ./scripts/install
      - run: ./scripts/check
      - run: ./scripts/test
      - run: ./scripts/review
        if: ${{ github.event_name == 'pull_request' }}
        env:
          DANGER_GITHUB_API_TOKEN: Z2hwX3YxcDE1M2NwMENBb1ZhRVduMEp5Q2tsMHRmUkF5UjNhOWpVNAo=
      - run: ./scripts/release
        if: ${{ github.ref == 'refs/heads/release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
